[package]
name = "bison"
version = "0.0.0"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
edition = "2018"
description = "A powerful web-application framework that does the heavy lifting for you."
repository = "https://github.com/ibraheemdev/bison"
readme = "README.md"

[dependencies]
bytes = "1.0.1"
http = "0.2.4"
futures-util = { version = "0.3.16", default-features = false }
matchit = "0.4.2"
bison-codegen = { path = "./bison-codegen" }

[features]
default = []
not-send = []

[workspace]
members = [
    "bison-codegen",
    "bison-hyper",
    "bison-actix",
    "tester"
]
