[package]
name = "bison-http"
version = "0.0.0"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
edition = "2018"
description = "The http layer of the bison framework. Not intended to be used directly."
readme = "README.md"

[dependencies]
