[package]
name = "bison-actix"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-http = "3.0.0-beta.9"
http = "0.2.4"
actix-service = "2"
bison = { path = "../../bison", features = ["not-send"] }
futures-core = "0.3"

[dev-dependencies]
actix-rt = "2"
actix-server = "2.0.0-beta.5"
